<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Molnar_Free_Tweaking_Utility</RootNamespace>
    <AssemblyName>Molnar</AssemblyName>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\Molnar.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Company>Krylo Central</Company>
    <Product>Molnar Free Tweaking Utility</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CuoreUI.Winforms" Version="2026.4.25" />
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.8" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\tweaks.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Molnar_Free_Tweaking_Utility.Properties</CustomToolNamespace>
    </EmbeddedResource>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
